# Generated manually for sitio_web
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AliadoLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('logo', models.ImageField(upload_to='sitio_web/aliados/')),
                ('sitio_web', models.URLField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.CreateModel(
            name='BloqueContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(choices=[('beneficios', 'Beneficios'), ('estadisticas', 'Estadísticas'), ('cta', 'Llamado a la acción'), ('nosotros_home', 'Nosotros en inicio')], max_length=60)),
                ('titulo', models.CharField(max_length=180)),
                ('subtitulo', models.CharField(blank=True, max_length=240)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, max_length=60)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='sitio_web/bloques/')),
                ('valor_numerico', models.PositiveIntegerField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={'ordering': ['clave', 'orden', 'id']},
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='sitio_web/seo/')),
                ('nombre_sitio', models.CharField(default='AulaPro Tecnología', max_length=150)),
                ('slogan', models.CharField(blank=True, max_length=220)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sitio_web/config/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='sitio_web/config/')),
                ('descripcion', models.TextField(blank=True)),
                ('sobre_nosotros', models.TextField(blank=True)),
                ('mision', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('telefonos', models.CharField(blank=True, max_length=220)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('horario', models.CharField(blank=True, max_length=255)),
                ('mapa_url', models.URLField(blank=True)),
                ('footer_text', models.CharField(blank=True, max_length=255)),
                ('color_primario', models.CharField(default='#1f3a93', max_length=20)),
                ('color_secundario', models.CharField(default='#00b4d8', max_length=20)),
                ('mostrar_testimonios', models.BooleanField(default=True)),
                ('mostrar_faqs', models.BooleanField(default=True)),
                ('mostrar_aliados', models.BooleanField(default=True)),
                ('mostrar_estadisticas', models.BooleanField(default=True)),
            ],
            options={'verbose_name': 'Configuración del sitio', 'verbose_name_plural': 'Configuración del sitio'},
        ),
        migrations.CreateModel(
            name='ContactoLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('empresa', models.CharField(blank=True, max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('servicio_interes', models.CharField(blank=True, max_length=180)),
                ('mensaje', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=160)),
                ('subtitulo', models.CharField(blank=True, max_length=220)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='sitio_web/hero/')),
                ('cta_texto', models.CharField(blank=True, max_length=60)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={'ordering': ['orden', 'id']},
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={'ordering': ['orden', 'id']},
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='sitio_web/seo/')),
                ('titulo', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('resumen', models.CharField(blank=True, max_length=220)),
                ('contenido', models.TextField(blank=True)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='sitio_web/paginas/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('mostrar_en_menu', models.BooleanField(default=False)),
            ],
            options={'ordering': ['orden', 'titulo']},
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pregunta', models.CharField(max_length=220)),
                ('respuesta', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={'ordering': ['orden', 'id']},
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='sitio_web/seo/')),
                ('titulo', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('cliente', models.CharField(blank=True, max_length=140)),
                ('categoria', models.CharField(blank=True, max_length=120)),
                ('resumen', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='sitio_web/proyectos/')),
                ('enlace_externo', models.URLField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
            ],
            options={'ordering': ['orden', '-created_at']},
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='sitio_web/seo/')),
                ('titulo', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('resumen', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(blank=True, help_text='Clase de icono (ejemplo: fa fa-cloud)', max_length=60)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='sitio_web/servicios/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
            ],
            options={'ordering': ['orden', 'titulo']},
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('cargo', models.CharField(blank=True, max_length=140)),
                ('empresa', models.CharField(blank=True, max_length=140)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='sitio_web/testimonios/')),
                ('comentario', models.TextField()),
                ('calificacion', models.PositiveSmallIntegerField(default=5)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=True)),
            ],
            options={'ordering': ['orden', 'id']},
        ),
        migrations.CreateModel(
            name='ProyectoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(upload_to='sitio_web/proyectos/galeria/')),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='sitio_web.proyecto')),
            ],
            options={'ordering': ['orden', 'id']},
        ),
    ]
