from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='sitio_web/seo/')),
                ('nombre_sitio', models.CharField(default='Tecnologías de Guatemala', max_length=150)),
                ('slogan', models.CharField(blank=True, max_length=220)),
                ('descripcion_corta', models.CharField(blank=True, max_length=260)),
                ('descripcion_larga', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sitio_web/config/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='sitio_web/config/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono_1', models.CharField(blank=True, max_length=60)),
                ('telefono_2', models.CharField(blank=True, max_length=60)),
                ('whatsapp', models.URLField(blank=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('horario', models.CharField(blank=True, max_length=255)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('footer_text', models.CharField(blank=True, max_length=255)),
                ('enlace_mapa', models.URLField(blank=True)),
                ('mapa_embed', models.TextField(blank=True)),
                ('color_primario', models.CharField(default='#7366ff', max_length=20)),
                ('color_secundario', models.CharField(default='#16c7f9', max_length=20)),
            ],
            options={'verbose_name': 'Configuración del sitio', 'verbose_name_plural': 'Configuración del sitio'},
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=160)),
                ('subtitulo', models.CharField(blank=True, max_length=220)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='sitio_web/hero/')),
                ('boton_texto', models.CharField(blank=True, max_length=60)),
                ('boton_url', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={'ordering': ['orden', 'id']},
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='sitio_web/seo/')),
                ('titulo', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('resumen', models.CharField(blank=True, max_length=220)),
                ('contenido', models.TextField(blank=True)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='sitio_web/paginas/')),
                ('publicada', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('mostrar_en_menu', models.BooleanField(default=False)),
            ],
            options={'ordering': ['orden', 'titulo']},
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='sitio_web/seo/')),
                ('titulo', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('resumen', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='sitio_web/servicios/')),
                ('icono', models.CharField(blank=True, help_text='Clase de icono (ejemplo: fa fa-cloud)', max_length=60)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
            ],
            options={'ordering': ['orden', 'titulo']},
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='sitio_web/seo/')),
                ('titulo', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('cliente', models.CharField(blank=True, max_length=140)),
                ('categoria', models.CharField(blank=True, max_length=120)),
                ('resumen', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='sitio_web/proyectos/')),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={'ordering': ['orden', '-created_at']},
        ),
        migrations.CreateModel(
            name='ProyectoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(upload_to='sitio_web/proyectos/galeria/')),
                ('titulo_opcional', models.CharField(blank=True, max_length=120)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='sitio_web.proyecto')),
            ],
            options={'ordering': ['orden', 'id']},
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('cargo', models.CharField(blank=True, max_length=140)),
                ('empresa', models.CharField(blank=True, max_length=140)),
                ('mensaje', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='sitio_web/testimonios/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={'ordering': ['orden', 'id']},
        ),
        migrations.CreateModel(
            name='AliadoLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('logo', models.ImageField(upload_to='sitio_web/aliados/')),
                ('url', models.URLField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pregunta', models.CharField(max_length=220)),
                ('respuesta', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={'ordering': ['orden', 'id']},
        ),
        migrations.CreateModel(
            name='BloqueContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(choices=[('fortalezas', 'Fortalezas'), ('soluciones', 'Soluciones'), ('estadisticas', 'Estadísticas'), ('cta', 'Llamado a la acción')], max_length=60)),
                ('titulo', models.CharField(max_length=180)),
                ('subtitulo', models.CharField(blank=True, max_length=240)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='sitio_web/bloques/')),
                ('icono', models.CharField(blank=True, max_length=60)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={'ordering': ['clave', 'orden', 'id']},
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('asunto', models.CharField(blank=True, max_length=180)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['-fecha_creacion']},
        ),
    ]
