# Generated by Django 5.1.4 on 2026-02-26 05:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=255, verbose_name='Nombre de la Institución')),
                ('nombre_institucion2', models.CharField(max_length=255, verbose_name='Nombre de la Institución2')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logotipos/', verbose_name='Logotipo')),
                ('tel', models.CharField(max_length=15, unique=True)),
                ('sitio_web', models.URLField(blank=True, max_length=255, null=True, verbose_name='Sitio Web')),
                ('correo', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('sitio_web', models.URLField(blank=True, max_length=255, null=True)),
                ('background_gafete', models.ImageField(blank=True, null=True, upload_to='logotipos2/')),
                ('gafete_ancho', models.PositiveIntegerField(default=880, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(1800)])),
                ('gafete_alto', models.PositiveIntegerField(default=565, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(1200)])),
                ('gafete_layout_json', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='dpi',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tipoc',
        ),
        migrations.AddField(
            model_name='empleado',
            name='codigo_personal',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cui',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleados_app_alumno',
        ),
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('es_activo', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_escolares', to='empleados_app.establecimiento')),
            ],
            options={
                'ordering': ['-anio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='empleados_app.establecimiento')),
            ],
            options={
                'ordering': ['establecimiento__nombre', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='empleados_app.establecimiento'),
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('jornada', models.CharField(blank=True, max_length=30)),
                ('seccion', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grados', to='empleados_app.carrera')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados_app.grado'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2200)])),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='empleados_app.empleado')),
                ('ciclo_escolar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='empleados_app.cicloescolar')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='empleados_app.grado')),
            ],
            options={
                'ordering': ['-created_at', 'alumno__apellidos', 'alumno__nombres'],
            },
        ),
        migrations.AddIndex(
            model_name='cicloescolar',
            index=models.Index(fields=['establecimiento', 'es_activo'], name='empleados_a_estable_ff9faa_idx'),
        ),
        migrations.AddIndex(
            model_name='cicloescolar',
            index=models.Index(fields=['establecimiento', 'anio'], name='empleados_a_estable_c5f9ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='cicloescolar',
            constraint=models.UniqueConstraint(fields=('establecimiento', 'nombre'), name='uq_ciclo_nombre_establecimiento'),
        ),
        migrations.AddConstraint(
            model_name='cicloescolar',
            constraint=models.UniqueConstraint(condition=models.Q(('es_activo', True)), fields=('establecimiento',), name='uq_ciclo_activo_por_establecimiento'),
        ),
        migrations.AlterUniqueTogether(
            name='carrera',
            unique_together={('establecimiento', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['grado', 'estado'], name='empleados_a_grado_i_0df73d_idx'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['grado', 'ciclo_escolar'], name='empleados_a_grado_i_19e6a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(condition=models.Q(('ciclo_escolar__isnull', False)), fields=('alumno', 'grado', 'ciclo_escolar'), name='uq_matricula_alumno_grado_ciclo_escolar'),
        ),
    ]
