# Generated by Django 5.1.4 on 2026-03-05 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "empleados_app",
            "0007_curso_cursodocente_asistencia_asistenciadetalle_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodoAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("BIMESTRE", "Bimestre"),
                            ("TRIMESTRE", "Trimestre"),
                            ("SEMESTRE", "Semestre"),
                        ],
                        default="BIMESTRE",
                        max_length=12,
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField()),
                ("nombre", models.CharField(max_length=80)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "curso_docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodos",
                        to="empleados_app.cursodocente",
                    ),
                ),
            ],
            options={
                "ordering": ["tipo", "numero"],
            },
        ),
        migrations.AddField(
            model_name="asistencia",
            name="periodo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asistencias",
                to="empleados_app.periodoacademico",
            ),
        ),
        migrations.AddConstraint(
            model_name="asistencia",
            constraint=models.UniqueConstraint(
                fields=("periodo", "fecha"), name="uq_asistencia_periodo_fecha"
            ),
        ),
        migrations.AddConstraint(
            model_name="periodoacademico",
            constraint=models.UniqueConstraint(
                fields=("curso_docente", "tipo", "numero"),
                name="uq_periodo_curso_docente_tipo_numero",
            ),
        ),
    ]
