# Generated by Django 5.1.4 on 2026-03-31 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados_app", "0011_establecimiento_background_gafete_posterior"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObservacionAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("academico", "Académico"),
                            ("conducta", "Conducta"),
                            ("asistencia", "Asistencia"),
                            ("otro", "Otro"),
                        ],
                        default="academico",
                        max_length=20,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("seguimiento", "En seguimiento"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="abierta",
                        max_length=15,
                    ),
                ),
                ("observacion", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observaciones",
                        to="empleados_app.empleado",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observaciones_alumnos_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["alumno", "fecha"],
                        name="empleados_a_alumno__d11800_idx",
                    ),
                    models.Index(
                        fields=["alumno", "estado"],
                        name="empleados_a_alumno__7b696c_idx",
                    ),
                ],
            },
        ),
    ]
