from django.urls import path

from . import views

app_name = "cms_web"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("", views.dashboard, name="dashboard"),
    path("configuracion/", views.ConfiguracionUpdateView.as_view(), name="configuracion"),
    path("heroes/", views.HeroList.as_view(), name="heroes"),
    path("heroes/nuevo/", views.HeroCreate.as_view(), name="hero_nuevo"),
    path("heroes/<int:pk>/editar/", views.HeroUpdate.as_view(), name="hero_editar"),
    path("heroes/<int:pk>/eliminar/", views.HeroDelete.as_view(), name="hero_eliminar"),
    path("paginas/", views.PaginaList.as_view(), name="paginas"),
    path("paginas/nuevo/", views.PaginaCreate.as_view(), name="pagina_nueva"),
    path("paginas/<int:pk>/editar/", views.PaginaUpdate.as_view(), name="pagina_editar"),
    path("paginas/<int:pk>/eliminar/", views.PaginaDelete.as_view(), name="pagina_eliminar"),
    path("servicios/", views.ServicioList.as_view(), name="servicios"),
    path("servicios/nuevo/", views.ServicioCreate.as_view(), name="servicio_nuevo"),
    path("servicios/<int:pk>/editar/", views.ServicioUpdate.as_view(), name="servicio_editar"),
    path("servicios/<int:pk>/eliminar/", views.ServicioDelete.as_view(), name="servicio_eliminar"),
    path("proyectos/", views.ProyectoList.as_view(), name="proyectos"),
    path("proyectos/nuevo/", views.ProyectoCreate.as_view(), name="proyecto_nuevo"),
    path("proyectos/<int:pk>/editar/", views.ProyectoUpdate.as_view(), name="proyecto_editar"),
    path("proyectos/<int:pk>/eliminar/", views.ProyectoDelete.as_view(), name="proyecto_eliminar"),
    path("proyectos/imagenes/", views.ProyectoImagenList.as_view(), name="proyecto_imagenes"),
    path("proyectos/imagenes/nueva/", views.ProyectoImagenCreate.as_view(), name="proyecto_imagen_nueva"),
    path("proyectos/imagenes/<int:pk>/editar/", views.ProyectoImagenUpdate.as_view(), name="proyecto_imagen_editar"),
    path("proyectos/imagenes/<int:pk>/eliminar/", views.ProyectoImagenDelete.as_view(), name="proyecto_imagen_eliminar"),
    path("testimonios/", views.TestimonioList.as_view(), name="testimonios"),
    path("testimonios/nuevo/", views.TestimonioCreate.as_view(), name="testimonio_nuevo"),
    path("testimonios/<int:pk>/editar/", views.TestimonioUpdate.as_view(), name="testimonio_editar"),
    path("testimonios/<int:pk>/eliminar/", views.TestimonioDelete.as_view(), name="testimonio_eliminar"),
    path("aliados/", views.AliadoList.as_view(), name="aliados"),
    path("aliados/nuevo/", views.AliadoCreate.as_view(), name="aliado_nuevo"),
    path("aliados/<int:pk>/editar/", views.AliadoUpdate.as_view(), name="aliado_editar"),
    path("aliados/<int:pk>/eliminar/", views.AliadoDelete.as_view(), name="aliado_eliminar"),
    path("faqs/", views.FaqList.as_view(), name="faqs"),
    path("faqs/nuevo/", views.FaqCreate.as_view(), name="faq_nueva"),
    path("faqs/<int:pk>/editar/", views.FaqUpdate.as_view(), name="faq_editar"),
    path("faqs/<int:pk>/eliminar/", views.FaqDelete.as_view(), name="faq_eliminar"),
    path("bloques/", views.BloqueList.as_view(), name="bloques"),
    path("bloques/nuevo/", views.BloqueCreate.as_view(), name="bloque_nuevo"),
    path("bloques/<int:pk>/editar/", views.BloqueUpdate.as_view(), name="bloque_editar"),
    path("bloques/<int:pk>/eliminar/", views.BloqueDelete.as_view(), name="bloque_eliminar"),
    path("mensajes/", views.MensajeList.as_view(), name="mensajes"),
    path("mensajes/<int:pk>/", views.mensaje_detalle, name="mensaje_detalle"),
]
